version: "3"
services:
  terraria:
    container_name: terraria
    restart: unless-stopped
    image: beardedio/terraria:vanilla-latest
    stdin_open: true
    tty: true
    environment:
      world: Fucktimans_Paradise.wld
    volumes:
      - $HOME/terraria/config:/config 
    ports:
      - 7777:7777
